// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfRa_Rrg0cWE8oPLa2Ft_xIH2mDdLrG5s',
    appId: '1:318764554112:web:59afe3810469f3205d5365',
    messagingSenderId: '318764554112',
    projectId: 'eduverse-cb718',
    authDomain: 'eduverse-cb718.firebaseapp.com',
    storageBucket: 'eduverse-cb718.firebasestorage.app',
    measurementId: 'G-259YL4B53M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1IZhtMx6fkc6JvsexoZsoOCbXJ4vZVCs',
    appId: '1:318764554112:android:228aab9b21060d4e5d5365',
    messagingSenderId: '318764554112',
    projectId: 'eduverse-cb718',
    storageBucket: 'eduverse-cb718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbLlIVE0XuB_an1y5TJm1P_MBR8C4T2Xc',
    appId: '1:318764554112:ios:ead88e52a09d936f5d5365',
    messagingSenderId: '318764554112',
    projectId: 'eduverse-cb718',
    storageBucket: 'eduverse-cb718.firebasestorage.app',
    iosBundleId: 'com.example.eduverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbLlIVE0XuB_an1y5TJm1P_MBR8C4T2Xc',
    appId: '1:318764554112:ios:ead88e52a09d936f5d5365',
    messagingSenderId: '318764554112',
    projectId: 'eduverse-cb718',
    storageBucket: 'eduverse-cb718.firebasestorage.app',
    iosBundleId: 'com.example.eduverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfRa_Rrg0cWE8oPLa2Ft_xIH2mDdLrG5s',
    appId: '1:318764554112:web:5618f8fffe48d0d45d5365',
    messagingSenderId: '318764554112',
    projectId: 'eduverse-cb718',
    authDomain: 'eduverse-cb718.firebaseapp.com',
    storageBucket: 'eduverse-cb718.firebasestorage.app',
    measurementId: 'G-SCPQ7Z5TJP',
  );
}
